language: ruby
rvm:
- ruby-2.0.0-p247
# rvm:
#   - 2.0.0-p247
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database todo_list_test;' -U postgres